# Generated by Django 2.2.5 on 2019-12-10 08:38

import annotate.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('labels', models.CharField(default='bird,bird_low', max_length=200, validators=[annotate.models.validate_string_list])),
                ('default_label', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(max_length=200, upload_to='')),
                ('format', models.CharField(choices=[('wav', 'wav'), ('mp3', 'mp3'), ('flac', 'flac'), ('ogg', 'ogg')], default='wav', max_length=10)),
                ('duration', models.FloatField(default=0)),
                ('prediction', models.TextField(default='', validators=[annotate.models.validate_json_list])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='', validators=[annotate.models.validate_json])),
                ('reviewed', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_by', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.AudioTrack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
